# Site settings
title: Interactify Backup
email: tas@interactify.dk
description: > # this means to ignore newlines until "baseurl:"
    Interactify
url: "http://interactify.dk" # the base hostname & protocol for your site - used for feed.xml
twitter_username: interactify
github_username:  interactify

# Build settings
markdown: kramdown